### ISSUE TITLE
Add isHorizontalScrollingEnabled option to mapView

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/mapbox-gl-native-android#105]
This is a feature request for the ability to easily **_disable horizontal scrolling_**. It’s currently possible to do this by restricting the bounds of the map (defining a northeast coordinate with a latitude of 90 and a southwest coordinate with a latitude of -90), but the scrolling behavior is not smooth. With this approach it’s necessary to swipe straight up and down or you bump into the east and west bounds.

It would be great to expose a simple option on the mapView for this behavior

cc @zugaldia 

iOS equivalent: https://github.com/mapbox/mapbox-gl-native-ios/issues/107

**Comment by tobrun** [comment]
fixed with https://github.com/mapbox/mapbox-gl-native-android/pull/156
