### ISSUE TITLE
Reduce collisions between LocationComponent and symbols on the map

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-android#114]
Collision detection between the `LocationComponent` and icons along a route line can occur so frequently that flickering appears to occur on the map. We should experiment with setting `ignore-placement: true` or reducing the size of `icon-padding` for the location puck. 

cc @LukasPaczos @mapbox/maps-ios

**Comment by LukasPaczos** [comment]
`LocationComponent` has all symbol collisions disabled by default, with no option to customize this behavior:
https://github.com/mapbox/mapbox-gl-native-android/blob/d8fc70eacdaef8e9ccfcea605028adace9799455/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LayerSourceProvider.java#L67-L68

I think we should be good to close here unless there's any other suspicious behavior @chloekraw?

**Comment by chloekraw** [comment]
Hmm yeah looks like we’re good to close here. Thanks @LukasPaczos!
