### ISSUE TITLE
Building arm-v7 and arm-v8 when deploying from IDE

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#115]
When deploying to a device (eg. arm-v8) in Android Studio, we build both arm-v7 as arm-v8:

```
ninja: Entering directory `MapboxGLAndroidSDK/.cxx/cmake/debug/arm64-v8a'
... // build arm-v8
ninja: Entering directory `MapboxGLAndroidSDK/.cxx/cmake/debug/armeabi-v7a'
... // build arm-v7
```

With old buildsystem this wasn't the case, we only build arm-v8.
Our cmd make targets are not impacted. 

@mapbox/maps-android

**Comment by Chaoba** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native-android/pull/341
