### ISSUE TITLE
who is developing mapbox ? kids ? 

### ISSUE THREAD

**Issue by c3ph3us** [mapbox/mapbox-gl-native-android#116]
8.5.0

with quick look at mapbox api i can say "this product" is uselles with such calls 

**1) "unknown" context calls to get shared preferences** 

like 

context.getSharedPreferences(MAPBOX_SHARED_PREFERENCES,Context.MODE_PRIVATE);

as looking through call

       public static synchronized Mapbox getInstance(@NonNull Context context, @Nullable String accessToken) {
         ThreadUtils.init(context);
         ThreadUtils.checkThread(TAG);
         if (INSTANCE == null) {
           **Context appContext = context.getApplicationContext();**
           FileSource.initializeFileDirsPaths(appContext);
            INSTANCE = new Mapbox(appContext, accessToken);

**then call to context.getSharedPreferences(blabla)**  wil give you inconsistents  results 

because  **you should honor the USER GIVEN CONTEXT**  and get the app context where u need it ... 

there is many why here ? but one most important please read lovely mapbox dev :)  is here: https://source.android.com/security/encryption/file-based 

ask self question what is behind those calls when user uses different apis like 19 and 28 and the "app works for example in background" with "keyguard lock is on or off" :) ? 

how will work your app and other user apps using your api after aosp api upgrade?

**2) all static calls to INSTANCE == null** 

like 

      public static TelemetryDefinition getTelemetry() {
        return INSTANCE.telemetry;
      }

maybe you could use your own method ?  com.mapbox.mapboxsdk.Mapbox#hasInstance() 

and du such thing like 

    return hasInstance() ? INSTANCE.telemetry : null;

why ? because my time :) and for your own reputation 

**3) use synchronization when its needed :)** 

for users: 

if you encounter an issue "with preferences weird behavior" just use a workaround :) 

        com.mapbox.mapboxsdk.Mapbox.getInstance(new android.content.ContextWrapper(applicationContext) {

                @Override
                public android.content.Context getApplicationContext() {
                    return this;
                }

                @Override
                public android.content.SharedPreferences getSharedPreferences(String name, int mode) {
                    android.content.Context ohLaLaLa = android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N ? applicationContext.createDeviceProtectedStorageContext() : applicationContext;
                    return ohLaLaLa.getSharedPreferences(name, mode);
                }
            }
            ,token);

**Comment by tobrun** [comment]
@c3ph3us thank you for reaching out, I do appreciate you given feedback but not the tone your are using.
