### ISSUE TITLE
Option to disable location tracking animation

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native-android#117]
@LukasPaczos commented on [Tue Jul 03 2018](https://github.com/mapbox/mapbox-plugins-android/issues/567)

We are hearing voices that smooth tracking animation puts a real stress on the battery consumption, CPU usage and introduces a delay. In order to improve the experience on lower-end devices, we could expose an option to disable the smooth animation.

/cc @danesfeder 

---

@LukasPaczos commented on [Tue Aug 28 2018](https://github.com/mapbox/mapbox-plugins-android/issues/567#issuecomment-416581358)

Unfortunately, because of the async rendering, disabling animations won't be feasible at this point as we are out of sync when updating the location source and the camera position at the same time.

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/16925074/44725526-c71b2100-aad5-11e8-827b-c17217f4b927.gif)

The work to unblock this use case is tracked in https://github.com/mapbox/mapbox-gl-native/issues/12752.

**Comment by LukasPaczos** [comment]
Disabling location animation should work reliably without rendering artifacts when using
- `LocationComponentActivationOptions#useSpecializedLocationLayer` set to `true`
- `LocationComponentOptions#trackingAnimationDurationMultiplier` set to `0`
