### ISSUE TITLE
Native crash on getClusterLeaves

### ISSUE THREAD

**Issue by Dkhusainov** [mapbox/mapbox-gl-native-android#121]
mapbox sdk: 8.6.0-beta.1

I'm using geojson source with `Point` and clustering. The crash happens when I'm callign `getClusterLeaves` on a clicked cluster

sample: code for `MapboxMap.OnMapClickListener`
```
  private fun handleMapClickForFeature(latLng: LatLng) {
    val pointF = map
      .projection
      .toScreenLocation(latLng)

    val queryRenderedFeatures = map.queryRenderedFeatures(pointF)

    //Point clusters
    val geoJsonSources = style
      .sources
      .filterIsInstance<GeoJsonSource>()
      .asSequence()
    queryRenderedFeatures
      .asSequence()
      .filter { feature -> feature.cluster }
      .flatMap { feature ->
        geoJsonSources
          .mapNotNull { source -> source.getClusterLeaves(feature, Long.MAX_VALUE, 0).features() }
      }
}
```

Exception:
```
java.lang.Error: The associated promise has been destructed prior to the associated state becoming ready.
        at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.nativeGetClusterLeaves(Native Method)
        at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.getClusterLeaves(GeoJsonSource.java:461)
```

**Comment by tobrun** [comment]
@Dkhusainov thank you for reaching out and using our products. I tried reproducing without luck so far. Are you able to produce this exception with each execution? Any other tips to reproduce this?

**Comment by Dkhusainov** [comment]
Here' a gist for crash:
https://gist.github.com/Dkhusainov/889c742984582edb51a0717098affc8c

Basically it happens because I call `getClusterLeaves` on a different GeoJsonSource witch the feature beloings to when it only has only SINGLE Point in it. You can uncomment DATA2 variable in the gist the test differenet behaviours.

**Comment by Dkhusainov** [comment]
@tobrun Any update? If it's not gonna be fixed anytime soon, can you provide a way to determine which clucster belongs to which `GeoJsonSource`?

**Comment by tobrun** [comment]
Could you give this a pass @Chaoba ?

**Comment by Dkhusainov** [comment]
Still not even a workaround? I just want to get points inside a clicked cluster from one of multiple `GeeJsonSource`.

**Comment by Dkhusainov** [comment]
Should I close the issue and create a new one?

**Comment by Chaoba** [comment]
@Dkhusainov this crash issue has been resolved and will be included in 9.3.0. If the closer does not belong to a Source, an empty `FeatureCollection` will be returned.

**Comment by Dkhusainov** [comment]
Thanks. 

ISome time ago I also found a workaround for it - querying each source to find out if a cluster belongs to it.

**Comment by Chaoba** [comment]
Close as it is resolved.
