### ISSUE TITLE
Update downstream AndroidX enabled dependencies

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#130]
We are moving forward on AndroidX migration. For customers not able to use jetifier, we need to make sure that all vendor modules are upgraded to AndroidX as well.

- [x] https://github.com/mapbox/mapbox-java/issues/1094 -> available in v5.0.0
- [x] https://github.com/mapbox/mapbox-gestures-android/issues/93 -> available in v0.6.0 
- [x] https://github.com/mapbox/mapbox-events-android/issues/446 -> availlable in v5.7.1
- [x] accounts library (closed source) -> available in 0.3.0

**Comment by edisonw** [comment]
telemetry will need to be updated here as well.

**Comment by tobrun** [comment]
Done!
