### ISSUE TITLE
MapboxStaticMap for multiple points on map

### ISSUE THREAD

**Issue by jishindev** [mapbox/mapbox-gl-native-android#139]
The `MapboxStaticMap` builder currently requires you to specify the center point and also the zoom level for it to work. 

```
val staticImage = MapboxStaticMap.builder()
	.accessToken(MAPBOX_ACCESS_TOKEN)
	.styleId(StaticMapCriteria.LIGHT_STYLE)
	.cameraPoint(Point.fromLngLat(longitude, latitude) // Image's center point on map
	.cameraZoom(13)
	.width(320) // Image width
	.height(320) // Image height
	.retina(true) // Retina 2x image will be returned
	.build())
```
This gets tricky to work with when you have multiple points to be shown within the map from which the static map url needs to be generated.

The center for a list of points can be extracted from the `LatLngBounds` class but not the zoom. 

So could we

1. Add support in `LatLngBounds`   to give us the zoom level
 **or**
2. Add support in the `MapboxStaticMap` api to accept `LatLngBounds` 

to cater to this use case?

**Comment by LukasPaczos** [comment]
Hey @jishindev, thanks for using Mapbox!

> Add support in LatLngBounds to give us the zoom level

This wouldn't be possible because you need the render's instance and pixel density to determine the correct zoom level.

> Add support in the MapboxStaticMap api to accept LatLngBounds

Looking at [the docs](https://docs.mapbox.com/api/maps/#retrieve-a-static-map-from-a-style), have you tried adding a blank overlay and specifying the `auto` value for the position?

/cc @mapbox/static-apis

**Comment by jishindev** [comment]
Thanks @LukasPaczos ,

I went through the api reference documentation now and found out that there is an equivalent for `position=auto` within the android mapbox sdk which is `MapboxStaticMap.Builder#cameraAuto(Boolean)`. 

May be this should be added to the official documentation for MapboxStaticMap so that it helps others here - https://docs.mapbox.com/android/java/overview/static-image/

Now I can use this - 
```
val staticImage = MapboxStaticMap.builder()
	.accessToken(MAPBOX_ACCESS_TOKEN)
	.styleId(StaticMapCriteria.LIGHT_STYLE)
	.cameraAuto(true)
	.width(320) // Image width
	.height(320) // Image height
	.retina(true) // Retina 2x image will be returned
	.build())
```
