### ISSUE TITLE
Move c++ code from upstream to this repository

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#143]
Capturing from @tmpsantos that we can start looking into removing the c++ code upstream so we can integrate it directly in this repository. Note that some other projects might be impacted by this migration and we need to double check what/when/how. 

@tarigo, we talked last week about consuming some bitmap c++ code from gl-native, note that this won't be possible after this migration.

cc @mapbox/maps-android

**Comment by tarigo** [comment]
Could we put it on hold till mapbox/mapbox-sdk#451 is ready?

**Comment by chloekraw** [comment]
@tobrun is this a duplicate of https://github.com/mapbox/mapbox-gl-native-android/issues/202?
