### ISSUE TITLE
Invalid value of mapbox.getProjection().getMeterPerPixelAtLatitude

### ISSUE THREAD

**Issue by maplestar0729** [mapbox/mapbox-gl-native-android#163]
I use the method in my project.
But, after ver 8.5.0, the value of method return is twice that of ver 8.4.0

**Comment by tobrun** [comment]
the value from 8.4.0 was taking in pixel ratio, making it screen ratio independent. Since pixel is in the name that was incorrect. If you want to get the same values as before (eg. getMetersPerDmAtLatittude). You will need to divide the value by pixel ratio.
