### ISSUE TITLE
MapView unable to retain state on navigate with AndroidX Navigation Components

### ISSUE THREAD

**Issue by BluestormDNA** [mapbox/mapbox-gl-native-android#179]
At the moment neither MapView nor Support map fragment can't retain the state of the view (like it is done when rotating the device) when navigating back to the original fragment wich contained the view using standard AndroidX Navigation Components.

Moving to any other fragment and going back will trigger the reload of the view thus giving a bad user experience.

GoogleMaps can retain its state even when navigating and returning back. Even if `onCreateView` and `getMapAsync `are called again. The only thing i noticed is that Navigation components don't trigger `onSaveInstanceState` (rotating the device do) so maybe it does some assumptions that are not allways true to try to save its state.

Is there something that can be done to retain the state?

**Comment by SamStenner** [comment]
This is a major issue, is there anything that can be done about this?

**Comment by djavid** [comment]
what about this issue? mapbox is completely unusable with android navigation, going to next fragment makes map flicker, and after returning back the map is dead
