### ISSUE TITLE
Within expression

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#185]
Similar to the work needed for https://github.com/mapbox/mapbox-gl-native-android/pull/171, we now need support for the `within` expression. 
see: https://github.com/mapbox/mapbox-gl-native/pull/16220 and https://github.com/mapbox/mapbox-gl-native/pull/16194 

cc @zmiao

**Comment by Chaoba** [comment]
Resolved in https://github.com/mapbox/mapbox-gl-native-android/pull/198.
