### ISSUE TITLE
Port circle-sort-key

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#197]
We already have symbol sort keys but now circle/line as well:
 - https://github.com/mapbox/mapbox-gl-native/pull/15875
 - https://github.com/mapbox/mapbox-gl-native/pull/15839

**Comment by chloekraw** [comment]
👋 looking at the [changes needed](https://github.com/mapbox/mapbox-gl-native-android/pull/209/files) for line- and fill-sort-key bindings, I'm interested in pairing with someone on this one after the JNI work is done.

The changes needed look fairly straightforward from what I can see: the main work is on CircleLayer.java and PropertyFactory.java, followed by adding tests. I think this would be a great experience for me to learn more about how to add tests to our SDK when we're implementing new features.

**Comment by Chaoba** [comment]
@chloekraw These changes are made by a script.

 If cycle-sort-key is ready in gl-native, we just need comment out this [line](https://github.com/mapbox/mapbox-gl-native-android/blob/f27b16562d3d15c8a0426134eaf52ad35a3d4c86/scripts/generate-style-code.js#L10)  and run the command `make android-style-code` all changes will be generated automatically.

**Comment by chloekraw** [comment]
@Chaoba oh wow, that's so cool!
