### ISSUE TITLE
Integrate Telemetry SDK v4.7.3

### ISSUE THREAD

**Issue by harvsu** [mapbox/mapbox-gl-native-android#200]
This ticket tracks the integration of Telemetry SDK v4.7.3 into Maps SDK and further follow ups on any issues/feedback post integration!!
@zugaldia @tobrun

**Comment by Chaoba** [comment]
Resolved in https://github.com/mapbox/mapbox-gl-native-android/pull/201

**Comment by zugaldia** [comment]
Thank you @Chaoba !
