### ISSUE TITLE
Expose new Mapbox style ids

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native-android#21]
New core style ids are launching soon. The expected date is October 28th, 2019. 

We'll want to make sure that the Maps SDK correctly exposes the various styles.

cc @aparlato

**Comment by tobrun** [comment]
cc @mapbox/maps-android

**Comment by langsmith** [comment]
This launch is delayed. The new launch date is TBD.

**Comment by chloekraw** [comment]
@langsmith @aparlato please reopen if the style ID change is planned again to let us know!
