### ISSUE TITLE
Release patch of tequila/unicorn: android-v8.6.3 / android-v9.0.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#210]
mapbox-gl-native made a patch release of [v1.2.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/maps-v1.2.2). We need to update `/vendor/mapbox-gl-native` of `release-unicorn/release-tequila` with this version and create a new tag for it (which starts a continuous deployment to bintray). For release tequila (v8.6.3), we need to validate how feasible this change is.

Additionally to the gl-native dependency update, I would like to include:
 - [ ] ~update of telemetry library [#201](https://github.com/mapbox/mapbox-gl-native-android/pull/201)~
 - [x] proguard fix for temetry events https://github.com/mapbox/mapbox-gl-native-android/pull/195 

Anything else?

cc @chloekraw @mapbox/maps-android

**Comment by tobrun** [comment]
We won't be updating the telemetry library this means that the AppTurnStileEvent can still be obfuscated. We can however fix that from our end through our proguard config. @Chaoba can you add a proguard config to keep [these](https://github.com/mapbox/mapbox-events-android/tree/master/libtelemetry/src/main/java/com/mapbox/android/telemetry) files ? and make this change to `release-unicorn` and `release-tequila` branches?

**Comment by tobrun** [comment]
Assigning myself, need to bring some build changes to the release branches. Aiming to release tomorrow.

**Comment by tobrun** [comment]
`release-unicorn` required build changes are moving at https://github.com/mapbox/mapbox-gl-native-android/pull/216. `release-tequila` won't be feasible to bring these changes in. I'm suggesting to release without inclusion of gl-native bump, only the proguard changes. 

cc @chloekraw

**Comment by chloekraw** [comment]
@tobrun `release-tequila` patch without gl-native version bump makes sense 👍

**Comment by chloekraw** [comment]
@tobrun our `release-unicorn` 9.0.x is currently on GL-Native's `release-unicorn`, or 1.0.0. I think we should avoid upgrading minor versions of GL-Native (or any dependencies) in patch releases, so let's upgrade to [1.0.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/maps-v1.0.1). (https://github.com/mapbox/mapbox-gl-native/tree/maps-v1.0.1)

Does that sound good to you?

cc/ @Chaoba

**Comment by chloekraw** [comment]
Done
