### ISSUE TITLE
Filtering by an array does not work

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native-android#213]
**Platform:** Android
**Mapbox SDK version:** 9.1.0-SNAPSHOT

### Steps to trigger behavior

**Option 1:**
```
val intArray = arrayOf<Int>(...)
val filteringExpression = Expression.match(
            get("IntPropertyName"),
            literal(intArray),
            literal(true),
            literal(false)
    )
layer.setFilter(filteringExpression)
```

**Option 2:**
```
val intArray = arrayOf<Int>(...)
val filteringExpression =  Expression.`in`(get("IntPropertyName"), literal(intArray))
layer.setFilter(filteringExpression)
```

### Expected behavior
Setting both Option 1 and Option 2 as filters should show only features, that have the value of IntPropertyName contained in intArray

### Actual behavior
Errors yielded, no features filtered.

Option 1:

> E/Mbgl: {<package>}[JNI]: Error setting filter: [2]: Branch labels must be numbers or strings.

Option 2:

> E/Mbgl: {<package>}[JNI]: Error setting filter: filter property must be a string

### But
The javadoc for "match" (Option 1) says:
> Selects the output whose label value matches the input value, or the fallback value if no match is found. The `input` can be any string or number expression. Each label can either be a single literal value **or an array of values**. If types of the input and keys don't match, or the input value doesn't exist, the expresion will fail without falling back to the default value.

The javadoc for "in" (Option 2) says:
> Retrieves whether an item exists in **an array** or a substring exists in a string.
Parameters:
needle - the item expression
haystack - the **array** or string expression

[Specs on the site](https://docs.mapbox.com/mapbox-gl-js/style-spec) also state that arrays are expected.

_But none works._ 

**So, how to compare a value against an array?**
And what is the best way in terms of performance, assuming it worked: `match`, `in`, or option below (`any`)?

Thanks!

PS. The only thing that is working for me is "emulating" those expressions with 
```
    Expression.any(
            eq(get(IntPropertyName), intValue1),
            eq(get(IntPropertyName), intValue2),
            ...
            eq(get(IntPropertyName), intValueN)
    )
```
but that is really bad, assuming there may be hundreds of items, if not more.

**Comment by Chaoba** [comment]
For option1, we do throw errors for array https://github.com/mapbox/mapbox-gl-native/blob/7d26a16489bd763a1bb0aa63a841369b3634fba0/src/mbgl/style/expression/match.cpp#L136  @tmpsantos is this a bug or a mistake in doc?

For option2, I tried to setFilter with the expression `in`, but not got this error message, it works well. @samfader  Can you create a project that could reproduce it? Thanks.
