### ISSUE TITLE
Download a map and when open other maps after that get black screen

### ISSUE THREAD

**Issue by nstele** [mapbox/mapbox-gl-native-android#266]
Start with a brief description below this line. -->
Download a region for use offline and try to open same map or other maps gets black screen (no layers)  I always have internet connection, I didn't try to use the saved region, just display the maps with internet connection.
If I kill the app and open it again it displays the map correctly 

### Steps to reproduce

 1. Open a map and download an offline region
 2. Go back to select to open other map after download (with internet connection)
 3. The map displays black background.

### Expected behavior

Open a map after download an offline region should show the map with correct background layer 

### Actual behavior
Shows black background

### Configuration

**Android versions:**  Android 8.0.0 and Android 9.0
**Device models:**  Tried with 10 devices
**Mapbox SDK versions:**  Latest version and    mapboxVersion = '8.1.0'

![Image from iOS (5)](https://user-images.githubusercontent.com/4140972/64704102-1b483780-d484-11e9-8501-58795e4ec2fe.jpg)
![Image from iOS (4)](https://user-images.githubusercontent.com/4140972/64704109-1edbbe80-d484-11e9-825a-0410fcddb0d7.jpg)

**Comment by ferdicus** [comment]
@LukasPaczos, sorry, late to the party, if you'd like to check out our implementation feel free to check out the mentioned ticket - thanks 🙇🏿
