### ISSUE TITLE
Configuring Mapbox key on Application class crashes on Nexus 5X API level 23

### ISSUE THREAD

**Issue by leocarona** [mapbox/mapbox-gl-native-android#277]
I have noticed this in both my apps.

Using

> implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0-alpha.1')

My Application class (full code [here](https://github.com/Hitchwiki/MyHitchhikingSpots-for-Android/blob/master/app/src/main/java/com/myhitchhikingspots/MyHitchhikingSpotsApplication.java)):
```
public class MyHitchhikingSpotsApplication extends MultiDexApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        //....
       Mapbox.getInstance(this, getResources().getString(R.string.mapBoxKey));
     }
}
```

Crash report:

> 
> java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
>      FATAL EXCEPTION: main
> Process: com.myhitchhikingspots, PID: 8300
> java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
> 	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
> 	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
> 	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
> 	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
> 	at com.myhitchhikingspots.MyHitchhikingSpotsApplication.onCreate(MyHitchhikingSpotsApplication.java:41)
> 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
> 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5417)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tobrun** [comment]
Following up on this in #416
