### ISSUE TITLE
Measure unit in circleRadius

### ISSUE THREAD

**Issue by simonvar** [mapbox/mapbox-gl-native-android#286]
Hello.

I have a circle layer and I want draw circle with certain radius in pixels.

As I noticed in CircleLayer method to set property circle radius has a float argument not in pixels.

How can I set circle radius in pixels?

````
val circleLayer = CircleLayer(...)
circleLayer.withProperties(
  PropertyFactory.circleRadius(pixels)
)
````

**Comment by tobrun** [comment]
Circle radius is in pixels, that public API takes in a floating point does't change it. The reasons why it's float is due to the style-spec type system https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-radius.

**Comment by simonvar** [comment]
Thanks for answer!

But something wrong in my project. 
I have 2 layers: 

1. SymbolLayer for image.
2. CircleLayer for circle below image.

Image size is radius of circle * 2:
```
 val bitmap = Glide.with(context)
                        .asBitmap()
                        .load((items[0] as ImageMapItem).url)
                        .submit(
                            pholeyMapAttrs.imageAttrs.activeRadius * 2,
                            pholeyMapAttrs.imageAttrs.activeRadius * 2
                        )
                        .get()
```

Layers initialization:
```
private val imageInactiveLayer = SymbolLayer(
        INACTIVE_IMAGE_LAYER_ID,
        sourceId
    ).apply {
        setFilter(filterExpression)
        withProperties(
            PropertyFactory.iconImage(get(properties.imageKey)),
            PropertyFactory.iconSize(1F)
        )
    }

    private val imageInactiveBackgroundLayer = CircleLayer(
        INACTIVE_BG_IMAGE_LAYER_ID,
        sourceId
    ).apply {
        setFilter(filterExpression)
        withProperties(
            PropertyFactory.circleColor(commonAttrs.inactiveColor),
            PropertyFactory.circleRadius(imageAttrs.inactiveRadius.toFloat())
        )
    }
```

In my case radius is 42px. (black line on screenshot is 42px).
![device-2020-03-23-120005](https://user-images.githubusercontent.com/10325034/77299709-ed2e9480-6cfd-11ea-913d-208c115bd237.png)

**Comment by tobrun** [comment]
interesting find @simonvar, it could be that you need to take the device pixel ratio in account:
```
imageAttrs.activeRadius.toFloat() / context.getResources().getDisplayMetrics().density
```

**Comment by simonvar** [comment]
@tobrun it works, thank you!
