### ISSUE TITLE
Cherry picks vanillashake releases

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#287]
This issue tracks pending cherry-picks from `master` -> `release-vanillashake`:
 - https://github.com/mapbox/mapbox-gl-native-android/issues/285
 - https://github.com/mapbox/mapbox-gl-native-android/pull/289#issuecomment-603970374

cc @Chaoba @chloekraw

**Comment by chloekraw** [comment]
Thanks @tobrun! In addition for the snapshotter, we'll need:
- https://github.com/mapbox/mapbox-gl-native-android/pull/268
- https://github.com/mapbox/mapbox-gl-native-android/pull/292
