### ISSUE TITLE
LocationComponent displayes broken updates even when not enabled 

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native-android#291]
```
mapboxMap.locationComponent.activateLocationComponent(
  LocationComponentActivationOptions.builder(this, style)
    .useDefaultLocationEngine(false)
    .build()
)
mapboxMap.locationComponent.cameraMode = CameraMode.TRACKING_GPS_NORTH

{ // location samples loop
mapboxMap.locationComponent.forceLocationUpdate(enhancedLocation)
}
```

When running the above scenario, the puck will start displaying and updating only the accuracy layer of the puck (changing its position as well) and also track the location with the camera, even though the component was never enabled, like:
```
mapboxMap.locationComponent.isLocationComponentEnabled = true
```

Until the above enable method is called, the component should ignore all updates.

**Comment by Chaoba** [comment]
Not able to reproduce this issue in https://github.com/mapbox/mapbox-gl-native-android/commit/09b2d4856958984448180d96dadd7b518b8716a4
