### ISSUE TITLE
`getFilter` crash when using `within` on JSONArray

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-android#303]
Logcat: 
```
java.lang.IllegalStateException
        at com.google.gson.JsonArray.getAsString(JsonArray.java:226)
        at com.mapbox.mapboxsdk.style.expressions.Expression$Converter.convert(Expression.java:4747)
        at com.mapbox.mapboxsdk.style.expressions.Expression$Converter.convert(Expression.java:4780)
        at com.mapbox.mapboxsdk.style.expressions.Expression$Converter.convert(Expression.java:4788)
        at com.mapbox.mapboxsdk.style.expressions.Expression$Converter.convert(Expression.java:4766)
        at com.mapbox.mapboxsdk.style.expressions.Expression$Converter.convert(Expression.java:4780)
        at com.mapbox.mapboxsdk.style.layers.SymbolLayer.getFilter(SymbolLayer.java:128)
```

Implementation:

```
     symbolLayer.setFilter(Expression.within(customPolygon));
     symbolLayer.getFilter()); 
```
Snippet of function that generates `customPolygon`:
```
...
        List<List<Point>> pointLists = new ArrayList<>();
        pointLists.add(points);
        return Polygon.fromLngLats(pointLists);
```

cc @mapbox/maps-android

**Comment by chloekraw** [comment]
@Chaoba has a possible workaround we could implement to unblock the release in the short term, but we've escalated this investigation upstream first.

**Comment by 1ec5** [comment]
This issue is [on the iOS project board](https://github.com/orgs/mapbox/projects/519#card-35528942) with the following note:

> Try to reproduce this Android issue with setting a filter using `within` and a JSONArray where the root cause is upstream

At a glance, I don’t see how this issue could be relevant to iOS/macOS, because the crash is upstream in GSON, which is an Android-only library.

**Comment by tobrun** [comment]
Glad to hear @1ec5 that this is not an issue for you.

For us, the issue comes from setting the following:

> ["within", {"json": "{"type":"Polygon","coordinates":[[[-77.0686734,38.9046766],[-77.0623326,38.9047934],[-77.0623434,38.9064632],[-77.0629013,38.9072063],[-77.0636415,38.9068473],[-77.063266,38.9063714],[-77.0632124,38.9055616],[-77.0691454,38.9054363],[-77.069124,38.9046682],[-77.0686734,38.9046766]]]}", "type": "Polygon"}]


But getting back :

> ["within",{"coordinates":[[[-77.0686734,38.9046766],[-77.0623326,38.9047934],[-77.0623434,38.9064632],[-77.0629013,38.9072063],[-77.0636415,38.9068473],[-77.063266,38.9063714],[-77.0632124,38.9055616],[-77.0691454,38.9054363],[-77.069124,38.9046682],[-77.0686734,38.9046766]]],"type":"Polygon"}]

@Chaoba could you look into why we are converting our input to the first block in `mapbox-java`? This doesn't look like valid json to me.

**Comment by Chaoba** [comment]
The reason why we need this key "json" is that we need to convert Object(map in android) to a Geojon object in this pr
https://github.com/mapbox/mapbox-gl-native/pull/16243

As @zmiao 's response in https://github.com/mapbox/mapbox-gl-native-team/issues/273#issuecomment-607136085 this issue should not be related with gl-native.

**Comment by tobrun** [comment]
let's move forward with the hack in the android conversion system, for v10.0.0 of the SDK we will support a different conversion system that wouldn't require any workarounds.
