### ISSUE TITLE
onLocationCameraTransitionFinished invoked immediately

### ISSUE THREAD

**Issue by grizzly** [mapbox/mapbox-gl-native-android#313]
class onLocationCameraTransitionListener implements OnLocationCameraTransitionListener {

                @Override
                public void onLocationCameraTransitionFinished(int cameraMode) {
                    locationComponent.zoomWhileTracking(16);
                }

                @Override
                public void onLocationCameraTransitionCanceled(int cameraMode) {

                }
            }

            //locationComponent.setCameraMode(CameraMode.TRACKING, new onLocationCameraTransitionListener());
            locationComponent.setCameraMode(CameraMode.TRACKING, 1000,5.0, 5.0, 5.0, new onLocationCameraTransitionListener());

onLocationCameraTransitionFinished is invoked immediately, not after 1000 ms. Zoom, Bearing and Tiled are ignored.

**Comment by Chaoba** [comment]
@grizzly Please refer to https://github.com/mapbox/mapbox-gl-native-android/blob/2ee650901325f6a6867421e2d9c729c538f81422/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java#L135

 If you are not in tracking mode or switch to none tracking mode, etc. the animation will not be triggered and onLocationCameraTransitionFinished is invoked immediately.
Feel free to reopen this issue if this not answers your question.
