### ISSUE TITLE
mapbox-android-accounts source and license issues

### ISSUE THREAD

**Issue by abaker** [mapbox/mapbox-gl-native-android#316]
mapbox-android-sdk has a dependency on mapbox-android-accounts, but there are a couple issues with the mapbox-android-accounts pom (as of 0.7.0)

* scm points to https://github.com/mapbox/mapbox-accounts-android, which returns a 404
* license is [Mapbox Terms of Service](https://www.mapbox.com/tos/)

My app uses mapbox-android-sdk and is published on F-Droid, so I just wanted to get this cleared up before someone complains. Thanks!

**Comment by chloekraw** [comment]
Hi @abaker, thanks for raising this issue. We're not sure what your concern is regarding the license.

> My app uses mapbox-android-sdk and is published on F-Droid, so I just wanted to get this cleared up before someone complains. 

Could you say more about what this complaint would be, and the relevance of F-Droid?

Also, could you say more about how you're using the Maps SDK? Do you have a Mapbox account?

Thanks!

**Comment by abaker** [comment]
Thanks for getting back to me! [My app](https://github.com/tasks/tasks) is a to-do list and users can use Mapbox Maps to set locations for tasks.

The F-Droid repository only allows free/libre software, and this requirement extends to dependencies as well. I was looking for a software license in the POM, e.g. in Mapbox Maps SDK for Android:

```
<licenses>                                                                    
  <license>                                                                   
    <name>BSD</name>                                                          
    <url>https://opensource.org/licenses/BSD-2-Clause</url>                   
    <distribution>repo</distribution>                                         
  </license>                                                                  
</licenses>
```

Since mapbox-android-accounts listed a TOS instead of a software license I tried to visit the SCM URL to find the software license, but that returned a 404

**Comment by abaker** [comment]
I just received an e-mail about Mapbox GL moving to a proprietary build licensed under the Mapbox Terms of Service, so I guess this licensing was intentional
