### ISSUE TITLE
Make Activities in test app exported

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-gl-native-android#321]
Android studio can start a specific Activity in the test app if set the launch option.
![image](https://user-images.githubusercontent.com/8577318/79179216-bc8fd580-7e39-11ea-9eda-48db22e0734e.png)

But it needs to add `exported = true` for this Activity in Manifest file. In order to simplify our development, it would be nice if we set `exported = true` for all Activities by default.

cc: @tobrun

**Comment by tobrun** [comment]
Sounds good to me
