### ISSUE TITLE
Icons are flickering when enabling tilt in cameraPosition

### ISSUE THREAD

**Issue by mrfaa** [mapbox/mapbox-gl-native-android#360]
Mapbox Version: 9.1.0

I made a clear Mapbox Demo App with nothing more than the basic setup: getting the map Instance, set a style, put some Symbols on the map (with SymbolOptions) and finally set the camera position.

When i set a tilt option to the CameraPosition the symbols are flickering at creation. See the video: https://nx5212.your-storageshare.de/s/KfTM9N2joDzA5Hi

When I don't use the tilt option, then noting flickers. See the video: https://nx5212.your-storageshare.de/s/tFEirbMconK9g73

Any thoughts about this behavior?

Thanks!

Best regards
Fabian

**Comment by mrfaa** [comment]
Any thoughts / updates on this behavior?

**Comment by zsoltbakos** [comment]
LocationComponent icon also blinks if tilt option is used.

**Comment by mrfaa** [comment]
I reference the issue also in the mapbox-gl-native repository. it seems to be a mapbox gl core issue. https://github.com/mapbox/mapbox-gl-native/issues/16473
