### ISSUE TITLE
Issue with Lat/Lng validation in LatLngBounds

### ISSUE THREAD

**Issue by ZiZasaurus** [mapbox/mapbox-gl-native-android#361]
In LatLngBounds.from the longitude values are annotated as needing to be between -180 and 180 but they cannot be restricted to that range since lonEast must be greater than lonWest so the way to show crossing the IDE is by having one of the values be outside the range.

The documentation is correct for longitude but the annotation is wrong which could create false Android lint warnings.

Is there a way that we can get a fix out for this?

**Comment by chloekraw** [comment]
@Chaoba could you take a look at this?

**Comment by Chaoba** [comment]
![image](https://user-images.githubusercontent.com/8577318/81376946-10d75e00-9137-11ea-86c3-93c7ad37e319.png)
@ziz I'm not seeing any lint warning in my Android studio. Can you specify what warnings did you see?

**Comment by ZiZasaurus** [comment]
Hi all, thank you for your work on this! It looks like TWC wasn't experiencing any problems - they  originally created a ticket because they were getting an exception, but later realized it was a bug in their code. But when investigating I noticed the annotations were wrong which could lead to a lint warning. Closing this ticket!
