### ISSUE TITLE
Investigate using system library loader

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-android#367]
The Maps SDK replaced `System.loadLibrary` with Relinker based on a recommendation from NDK 19's changelog entry:
> ndk-depends has been removed. We believe that ReLinker is a better solution to native library loading issues on old Android versions. 

We did so, and later replaced Relinker with Soloader due to stability issues. However, quite a few issues reported have been linked to Soloader as well. We should investigate returning to `System.loadLibrary`, particularly since the need to support "old Android versions" is less today.

cc @mapbox/maps-android @zugaldia

**Comment by zugaldia** [comment]
Interesting, it's my understanding that both ReLinker and SoLoader use `System.loadLibrary` under the hood but add protections for certain Android API levels. In any case, as long as the loader remains a module the developer can customize we should be good here.
