### ISSUE TITLE
Distinguish sort order and rendering order

### ISSUE THREAD

**Issue by Nonda95** [mapbox/mapbox-gl-native-android#379]
I've disabled icon overlapping with negative icon padding to allow symbols to be partially overlapped, but then my symbols with higher priority are drawn below lower priority symbols.

In symbol-sort-key property documentation there's the info:
```
Features with a higher sort key will appear above features with a lower sort key when they overlap. Features with a lower sort key will have priority over other features when doing placement.
```
Is there any option that higher priority symbols will have priority during the placement and will appear above other features?

**Comment by ansis** [comment]
> Is there any option that higher priority symbols will have priority during the placement and will appear above other features?

There is no explicit option but you can flip the priority with a `["-", ...]` expression. For example, if you have `"symbol-sort-key": ["get", "priority"]` flipping it would look something like `"symbol-sort-key": ["-", ["get", "priority"]]` in your style

**Comment by chloekraw** [comment]
The equivalent at runtime on Android would be: 
```
symbolLayer.setProperties(PropertyFactory.symbolSortKey(subtract(get("priority")))); 
```
