### ISSUE TITLE
Feature Request: Undeprecate MapBoxMapOptions Default Constructor

### ISSUE THREAD

**Issue by eygraber** [mapbox/mapbox-gl-native-android#388]
`AttributeSet` is not a great API to force users into, and I don't want to put a lot of work into deprecated APIs in case they disappear one day.

**Comment by Chaoba** [comment]
You can pass null to use default config if you don't want to create `AttributeSet` instance.
Then set its properties separately. 
```
 MapboxMapOptions options = MapboxMapOptions.createFromAttributes(application, null);

```

**Comment by eygraber** [comment]
My apologies. I thought all of the functions on `MapboxMapOptions` were deprecated as well, and `AttributeSet` was the only way to set the options.
