### ISSUE TITLE
[Android] New camera update padding api - no way to specify zoom+padding for latlng update.

### ISSUE THREAD

**Issue by freszu** [mapbox/mapbox-gl-native-android#39]
Currently we are using old method setPadding + CameraUpdateFactory.newLatLngZoom. Noticing the deprecation and wanting to get rid of it i realized this is not covered in new api though it seems it's referred in documentation:
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java#L140

### Expected behavior

There is counterpart for depreacted api

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 
8.4.0 + current master

**Comment by LukasPaczos** [comment]
Thanks for pointing out the docs error!

There's no convenience method for LatLng + zoom + padding, but you can use:
```
mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(
        new CameraPosition.Builder()
        .target(latLng)
        .zoom(zoom)
        .padding(padding)
        .build()
));
```
