### ISSUE TITLE
Add TelemetryImpl#setBaseUrl

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-android#393]
For 9.3.0-alpha.1, we need a new entry in https://github.com/mapbox/mapbox-gl-native-android/blob/master/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TelemetryDefinition.java and provide the glue to call into the new setBaseUrl function exposed by telemetry in https://github.com/mapbox/mapbox-gl-native-android/blob/master/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java.

cc @tobrun @mapbox/maps-android

**Comment by Chaoba** [comment]
We can do the configuration through META-DATA after next release of telemetry.
