### ISSUE TITLE
Memory leak in native code

### ISSUE THREAD

**Issue by Dkhusainov** [mapbox/mapbox-gl-native-android#405]
Mapbox: 9.2.0
Reproducer: https://gist.github.com/Dkhusainov/4cc6605692961c6c075196668a1d54c2

Open AS profiler while running the reproducer and see this picture:
![leak](https://user-images.githubusercontent.com/7382654/83359335-45c78100-a382-11ea-9c70-ce8b5b968dba.PNG)

**Comment by Chaoba** [comment]
@Dkhusainov Thanks for your reporting. I am able to reproduce this issue locally. By adding log I find the possible reason for this leak is that the deconstruction method of Source.cpp is never called. Maybe there is a strong reference that is still holding this instance.

I have updated my test branch: https://github.com/mapbox/mapbox-gl-native-android/commits/kl-source-leak

cc: @mapbox/maps-android
