### ISSUE TITLE
Compiling under Android R (Android 11) throws error

### ISSUE THREAD

**Issue by mrfaa** [mapbox/mapbox-gl-native-android#425]
Hi together,

has anybody tried to compile the android mapbox SDK under Android R (Android 11)?

I created a blank android app from scatch and added the mapbox dependency (9.2.0) like noted in https://docs.mapbox.com/android/maps/overview/#install-the-maps-sdk.

In my android project i used
```
compileSdkVersion 'android-R'
targetSdkVersion 'R'
```

This leads to following crash at `mapView.onCreate(savedInstanceState)`

```
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber

       .....
     Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        ...

com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8718)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2941)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2905)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:165)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:303)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:7989)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)`
```

Any thoughts about this behavior?

My virtual device: API R; Target Android 10.0+ (Google Play)

Hint:
````
compileSdkVersion '29'
targetSdkVersion '29'
````
is working.

Thanks!
Fabian

**Comment by Bakeneko** [comment]
[TelemetryUtils.obtainCellularNetworkType()](https://github.com/mapbox/mapbox-events-android/blob/296980a8b2cc6834f4654fc069a5d3e007220361/libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java#L163) is calling [TelephonyManager.getNetworkType()](https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkType()) which is deprecated in api level 30. 

👉 mapbox/mapbox-events-android#482

**Comment by SamStenner** [comment]
This is a pretty serious bug, and will produce privacy concerns from users if not fixed. Any app that accesses location already requires the trust of the user, and requesting access to extraneous permissions will hurt that trust.

**Comment by knov** [comment]
Thank you for reporting this issue. We will be looking into this.
cc @mapbox/mobile-telemetry-android

**Comment by moritzzzzz** [comment]
The problem has been fixed in [Mapbox-Android-Telemetry-6.1.0](https://github.com/mapbox/mapbox-events-android/releases/tag/telem-6.1.0-core-3.0.0) and will be released with a future version of the Mapbox Maps SDK for Android.

**Comment by SarthakWhoop** [comment]
Developer from another project facing a similar crash. 
Can we get a timeline on when will it be released in the Mapbox Maps SDK for Android?

**Comment by prfarlow1** [comment]
With the new fix out, are we expected to add the `READ_PHONE_STATE` permission to our apps that use MapBox?

**Comment by tobrun** [comment]
> With the new fix out, are we expected to add the READ_PHONE_STATE permission to our apps that use MapBox?

We haven't added this permission to any library manifest or are requesting this permission at runtime.

**Comment by rpadma** [comment]
@tobrun - I'm facing an issue if we don't add the `READ_PHONE_STATE` permission on Android 11. It does work on Android os 10 and below without the `READ_PHONE_STATE`.  To make it work on Android 11 -  I had to add the permission and request the runtime permission from user before loading the map and request location. 
Here is the log trace- 
```
java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10265 does not have android.permission.READ_PHONE_STATE.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3356)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3500)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
I saw in the thread which says this issue is fixed in `Mapbox-Android-Telemetry-6.1.0` . Let me know if you need any additional information.

**Comment by SamStenner** [comment]
> @tobrun - I'm facing an issue if we don't add the `READ_PHONE_STATE` permission on Android 11. It does work on Android os 10 and below without the `READ_PHONE_STATE`.  To make it work on Android 11 -  I had to add the permission and request the runtime permission from the user before loading the map and request location. 
> Here is the log trace- 
> ```
> java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10265 does not have android.permission.READ_PHONE_STATE.
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3356)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3500)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7523)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
> ```
> I saw in the thread which says this issue is fixed in `Mapbox-Android-Telemetry-6.1.0` . Let me know if you need any additional information. 

As a previous comment states, the issue you're having is fixed and will be available in a future version of the Mapbox SDK for Android.

**Comment by rpadma** [comment]
@SamStenner - Thanks for the quick response. Is there any approximate timeline when the future version of the Mapbox SDK for android will be available for testing?

**Comment by SamStenner** [comment]
> @SamStenner - Thanks for the quick response. Is there any approximate timeline when the future version of the Mapbox SDK for Android will be available for testing?

No idea, sorry 😢 I'm just a random dude.

**Comment by rpadma** [comment]
> > @tobrun - I'm facing an issue if we don't add the `READ_PHONE_STATE` permission on Android 11. It does work on Android os 10 and below without the `READ_PHONE_STATE`.  To make it work on Android 11 -  I had to add the permission and request the runtime permission from the user before loading the map and request location.
> > Here is the log trace-
> > ```
> > java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10265 does not have android.permission.READ_PHONE_STATE.
> >         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3356)
> >         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3500)
> >         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
> >         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> >         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> >         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
> >         at android.os.Handler.dispatchMessage(Handler.java:106)
> >         at android.os.Looper.loop(Looper.java:223)
> >         at android.app.ActivityThread.main(ActivityThread.java:7523)
> >         at java.lang.reflect.Method.invoke(Native Method)
> >         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> >         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
> > ```
> > 
> > 
> > I saw in the thread which says this issue is fixed in `Mapbox-Android-Telemetry-6.1.0` . Let me know if you need any additional information.
> 
> As a previous comment states, the issue you're having is fixed and will be available in a future version of the Mapbox SDK for Android.

@tobrun - Same question☝️ It would be great if you can provide us with an approx timeline when the next version will be available for testing. Thank you.

**Comment by tobrun** [comment]
It's fixed with https://github.com/mapbox/mapbox-events-android/releases/tag/telem-6.1.0-core-3.0.0, we will be patching this into a 9.3.2 and will also be available with 9.4.0. For 9.3.2, we are waiting for another issue to be patched before releasing it.

This all said, you can already incorporate the change with any Android Maps SDK that uses 6.x telemetry. Gradle is smart enough to selectively pick dependencies. If you add the following to your build file:

````
implementation com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0
```

It will discard the packaged telemetry library from the maps sdk and use 6.1.0 instead.

**Comment by rpadma** [comment]
> implementation com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0

@tobrun - Thanks for the update.

**Comment by thomaswoodfin2** [comment]
I received the same crash.  This is a strange permission to request the user to accept for accessing maps.

**Comment by rommansabbir** [comment]
![image](https://user-images.githubusercontent.com/25950083/103459383-3d309200-4d39-11eb-93ce-715875423c82.png)


`E/TelemetryUtils: java.lang.SecurityException: getDataNetworkTypeForSubscriber`

Android Studio: 4.11
Emulator: Pixel_2_API_29
Mapbox Version: 9.2.0

**Comment by ghadeeraqraa1992** [comment]
I have the same issue on my react native project using 
@react-native-mapbox-gl/maps library

**Comment by djdance** [comment]
my favorite solution for years - remove this string completely
 `mapView.onCreate(savedInstanceState);`
and it will work as expected
