### ISSUE TITLE
Integrate user animation handling

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#467]
In an upcoming gl-native release, we will have the ability to flag that an platform driven animation is ocrruring (similar to the setGestureInProgresss/isGestureInProgress).

**Comment by tobrun** [comment]
Expose Map::setUserAnimationInProgress()/isUserAnimationInProgress()

**Comment by LukasPaczos** [comment]
For reference, `LocationComponent` integration happened in https://github.com/mapbox/mapbox-gl-native-android/pull/501 and https://github.com/mapbox/mapbox-gl-native-android/pull/504.
