### ISSUE TITLE
Inappropriate country research response 

### ISSUE THREAD

**Issue by mastro1984** [mapbox/mapbox-gl-native-android#469]
Hi i am using mapbox api to search country and city according to user input. If I am looking for Paris the query answers me correctly Paris France, but if I am looking for "PARIGI" (in Italian) I am back to Paris ("Indonesia"). Do you have a way to sort the results based on the importance of the place without using the language?
ANdroid version sdk 9.2.0
my settings

 val client = MapboxGeocoding.builder()
            .accessToken(mapBoxAccessToken)
            .query(place) --> "PARIGI"
            .geocodingTypes(GeocodingCriteria.TYPE_PLACE,GeocodingCriteria.TYPE_COUNTRY)
            .mode(GeocodingCriteria.MODE_PLACES) 
            .build()

Thanks in advance
Emanuele.

**Comment by tobrun** [comment]
Emanuele, this issue is not related to the project found in this repository.
In any case, to answer your question, you will need to use the proximity option: 
```
Bias the response to favor results that are closer to this location, provided as two comma-separated coordinates in longitude,latitude order.
```
as shown in the documentation: https://docs.mapbox.com/api/search/#forward-geocoding

**Comment by mastro1984** [comment]
Ciao @tobrun 
Thank you for your answer.

You could indicate me correct project because from the mapbox website I am sent back here.

Proximity flag does not solve my issue, because if I am "Indonesia" and I am looking for "PARIGI" I would still like to have "Paris France" as my first option, not "Paris Indonesia".

I'm looking for an option (if any) that sorts the results based on the importance of the place.

Thanks in advance,
Emanuele.
