### ISSUE TITLE
Map#setUserAnimationInProgress - LocationComponent integration

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#492]
Exposing hooks for animation handling were added in https://github.com/mapbox/mapbox-gl-native-android/pull/491. We need to optimize our location component code to use them.

Atm, I'm thinking we should call `setUserAnimationInProgress` when tracking mode is enabled and disable when tracking mode gets dismissed. If that doesn't provide the UX we are looking for we could alternatively call this setup with each easeTo invocation.

cc @Chaoba  @LukasPaczos

**Comment by Chaoba** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native-android/pull/501
