### ISSUE TITLE
Enable offline regions that cross the 180th meridian

### ISSUE THREAD

**Issue by knov** [mapbox/mapbox-gl-native-android#494]
There is an error thrown when crossing the 180th meridian with Offline Regions that throws 
`Provided OfflineRegionDefinition doesn't fit the world bounds`

**Expected behavior**
It is possible to enter coordinates with longitudes outside of -180-180 in the offline tile count estimator (see https://docs.mapbox.com/playground/offline-estimator/). Users should be able to download regions that cross the 180th meridian.

We should support the LatLngBounds like [10, -170, -10, -190], however while validating the OfflineRegionDefinition in OfflineManager we do check if the bounds are using wrapped coordinates:

```
private boolean isValidOfflineRegionDefinition(OfflineRegionDefinition definition) {
    return LatLngBounds.world().contains(definition.getBounds());
}
```

And will throw exception if the longitude is outside [-180, 180]. Seems like the Offline Region doesn't support download a single bound across the meridian.

We should adjust this logic to allow for bounds across the meridian and remove the `isValidOfflineRegionDefinition` validation.

cc @pengdev @tobrun

**Comment by tobrun** [comment]
merged in #495
