### ISSUE TITLE
Mapbox android does not get new tile data after reseeding tiles in server side.

### ISSUE THREAD

**Issue by harry-wilson** [mapbox/mapbox-gl-native-android#514]
We've used Mapbox android SDK render vector tiles created by GeoServer and it works fine. But the problem is after reseeding new tile data produced by GeoServer, map on android device does not get new tiles until we clear cache of device from storage settings. In this [blog](https://blog.mapbox.com/new-cache-management-controls-for-mapbox-sdks-2be0302f9ba) stated that new map tiles are refreshed after 12 hours but it didn't happen after 1 day.

**Comment by tobrun** [comment]
@harry-wilson tile eviction/refresh policy is driven through the http specification. We aren't enforcing these 12 hours in code, that is driven by the server. When we store a tile in the db, we add timestamp in the expires column (extracted from the http request). You will have to dig into your server configuration to fix this. Afaik works as designed on our end when using mapbox hosted tiles.

**Comment by harry-wilson** [comment]
@tobrun I've check the HTTP headers but I can't find the problem. 

```
Cache-Control: max-age=2629743, must-revalidate
Content-Length: 2309
Content-Type: application/vnd.mapbox-vector-tile
Date: Sat, 15 Aug 2020 13:52:02 GMT
Expires: Mon, 14 Sep 2020 22:27:35 GMT
geowebcache-cache-result: HIT
geowebcache-crs: EPSG:900913
geowebcache-gridset: EPSG:900913
geowebcache-tile-bounds: 5741949.563983154,4263963.185266722,5742561.060209349,4264574.681492921
geowebcache-tile-index: [42158, 39741, 16]
Last-Modified: Sat, 15 Aug 2020 11:56:45 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```
