### ISSUE TITLE
MapSnapshotter crash

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-gl-native-android#551]
`MapSnapshotter` throws native exception. I've met it at [my pull](https://github.com/mapbox/mapbox-navigation-android/pull/3441). It happens with `Nexus 5` only(API 21)(firebase robotest [one](https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/8094012912059041327/executions/bs.8128b0899d7bf89/), [two](https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/5888843953099279755/executions/bs.1fa315d8ccf1ddc3/))

<details>
  <summary>Crash log</summary>

> 08-17 05:50:12.434: W/Mbgl(14259): {Snapshotter}[OpenGL]: Not using Vertex Array Objects
> 08-17 05:50:12.435: W/Adreno-ES20(14259): <core_glRenderbufferStorage:659>: GL_INVALID_VALUE
> 08-17 05:50:12.437: A/libc(14259): /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::runtime_error: Couldn't create framebuffer: incomplete attachment" failed
> 08-17 05:50:12.437: A/libc(14259): Fatal signal 6 (SIGABRT), code -6 in tid 16124 (Snapshotter)

</details>

MapsSDK version: `9.4.0`

**cc** @mapbox/maps-android @Guardiola31337 @LukasPaczos

**Comment by alexshalamov** [comment]
@RingerJK Do you know what width and height were used for snapshotter? Looking at https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glRenderbufferStorage.xml, issue could be caused by an invalid size.

**Comment by RingerJK** [comment]
@alexshalamov I've logged it. `MapSnapshotter.Options` are `width = 1080`, `height = 1701 `, which are actually `measuredWidth` and `measuredHeight` of MapView

**Comment by alexshalamov** [comment]
@RingerJK and what pixel ratio do you pass to the options?

**Comment by RingerJK** [comment]
@alexshalamov pixel ratio is taken from `context.resources.displayMetrics.density`, value is `3.0` for `Nexus 5`. 
I didn't see similar issues with other real or emulator devices. And get crash with firebase tests only(but I don't have `Nexus 5` to test it on my side 😞 ) 

I've changed width and height as at the Samples (took measureHeight/Width from ImageView where snapshot is gonna fill to)
https://github.com/mapbox/mapbox-gl-native-android/blob/cc1c8814a37cdec923a03a9cb9e3fbb48b37491d/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/turf/MapSnapshotterWithinExpression.kt#L132
after this I didn't observe the native crash. 

But still seems that it's a problem, that should be resolved, don't it?

**Comment by alexshalamov** [comment]
@RingerJK I will try to reproduce issue, maybe view is not yet laid-out, thus measured view dimensions could be 0. How did you get width & height before you changed code to:
```kotlin
val options = MapSnapshotter.Options(imageView.measuredWidth / 2, imageView.measuredHeight / 2)
```

**Comment by RingerJK** [comment]
@alexshalamov I've got it from mapView so it looked like(I didn't divide sizes on 2 )
```
val options = MapSnapshotter.Options(mapView.measuredWidth, mapView.measuredHeight)
```

**Comment by alexshalamov** [comment]
One issue might be is that, when following values are passed to options: pixel ratio: 3.0, width: 1080, height: 1701, snapshotter would require 3240x5103 framebuffer and Nexus5, that is a quite an old device, might not support such large framebuffer.

**Comment by RingerJK** [comment]
@alexshalamov do we have an opportunity to check it? I mean this feature is important for Navigation team, we're gonna use it as a part of SDK. Would be great to figure out why the crash happens

**Comment by kiryldz** [comment]
@alexshalamov @RingerJK as far as I see Nexus 5 has Adreno 330 GPU.
That actually means that `GL_MAX_RENDERBUFFER_SIZE = 4096` thus requesting 3240x5103 framebuffer will cause GL error `GL_INVALID_VALUE`.

![image](https://user-images.githubusercontent.com/15800566/92591002-c9f4a300-f2a5-11ea-8235-ed9e03ae7faa.png)

@RingerJK - could you try passing less values (e.g. divide dimensions by 2) and see if CI will fail?

**Comment by RingerJK** [comment]
@kiryldz did it, CI hasn't failed from that moment. Do you have a recommendation how to prevent this crash?

**Comment by alexshalamov** [comment]
@RingerJK @kiryldz native snapshotter expect size to be in device independent pixels, therefore, if developer provides pixel ratio other than 1, size has to be converted to device pixels.

```kotlin
MapSnapshotter.Options(mapView.measuredWidth / pixelRatio, mapView.measuredHeight / pixelRatio).withPixelRatio(pixelRatio)
```

I will make an issue (fix) for checking whether provided size do not exceed `GL_MAX_RENDERBUFFER_SIZE`

**Comment by RingerJK** [comment]
after discussion: [that is client side fix](https://github.com/mapbox/mapbox-gl-native-android/issues/551#issuecomment-689511604), issue will be solved at next Maps' major version(`10.x.x`)

**cc** @alexshalamov @kiryldz
