### ISSUE TITLE
May crash with wstring_convert: to_bytes error when using 9.5.0

### ISSUE THREAD

**Issue by ystsoi** [mapbox/mapbox-gl-native-android#581]
I found that 9.5.0 may crash when zoom the map to some places. 9.4.0 is OK.

Please try the following code:
```
mapView.getMapAsync(new OnMapReadyCallback() {
    @Override
    public void onMapReady(@NonNull final MapboxMap mapboxMap) {

        mapboxMap.setStyle(Style.MAPBOX_STREETS, new Style.OnStyleLoaded() {
            @Override
            public void onStyleLoaded(@NonNull final Style style) {

                // Map is set up and the style has loaded. Now you can add data or make other map adjustments
                LocalizationPlugin localizationPlugin = new LocalizationPlugin(mapView, mapboxMap, style);
                localizationPlugin.setMapLanguage(MapLocale.CHINESE_HANT);

            }
        });
        mapboxMap.setCameraPosition(new CameraPosition.Builder().target(new LatLng(22.4636295, 114.2909171)).zoom(16).build());

    }
});
```

It will produce the following error:
```
java.lang.Error: wstring_convert: to_bytes error
    at com.mapbox.mapboxsdk.maps.renderer.MapRendererRunnable.run(Native Method)
    at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.MapboxGLSurfaceView$GLThread.guardedRun(MapboxGLSurfaceView.java:758)
    at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.MapboxGLSurfaceView$GLThread.run(MapboxGLSurfaceView.java:568)
```

I guess this may be due to a supplementary character in that area. Please check.

**Comment by ystsoi** [comment]
It seems that 9.6.0-alpha.1 has fixed this.

**Comment by tasomaniac** [comment]
We are also facing the same issue. Interestingly we updated the MapBox SDK for another crash fix related to map styling. That crash was fixed. But now we have this and it is happening even more frequently.

Is there any other workaround to mitigate this apart from using the alpha version?

**Comment by tobrun** [comment]
We fixed this internally and will be following up with a 9.5.1patch release before the 9.6.0 final (which also includes the fix). 
Thank you all for reaching out!

**Comment by kiryldz** [comment]
@ystsoi @tasomaniac 9.5.1 patch release is out, please check it out.

**Comment by ystsoi** [comment]
Checked that this issue does not exist in 9.5.1. Thanks.
