### ISSUE TITLE
SDK issue

### ISSUE THREAD

**Issue by nilsorathiya** [mapbox/mapbox-gl-native-android#593]
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0.

**Comment by sandeepsingh91** [comment]
i got the same issue...

**Comment by tobrun** [comment]
Since a couple of releases we moved away from normal maven central setup to a mapbox hosted maven. 
Configuration instructions can be found [here](https://github.com/mapbox/mapbox-gl-native-android#setup-mapbox-access-token-for-dependency-download).
