### ISSUE TITLE
Direct download missing dependency

### ISSUE THREAD

**Issue by Dkhusainov** [mapbox/mapbox-gl-native-android#594]
I downloaded `mapbox-android-sdk` and published it to local repository _with the provided pom_. Every dependency got resolved except `mapbox-android-sdk-gl-core`. How do I get it without doing token authentication thing?

**Comment by tobrun** [comment]
Thank you for flagging, we are looking into this. For now can you use the maven hosted dependency instead to pull in your binaries.

**Comment by mloskot** [comment]
@Dkhusainov  Was it throwing HTTP 401 too?  https://github.com/mapbox/mapbox-gl-native-android/issues/631
