### ISSUE TITLE
LocationComponent Pulse Graphical Issue

### ISSUE THREAD

**Issue by findyourexit** [mapbox/mapbox-gl-native-android#611]
Upon updating to Maps SDK (for Android) **9.5.0**, I've noticed a visual peculiarity occurring when I enable `LocationComponent` pulsing. The issue is immediately apparent as the pulse does not smoothly "pulse" outward, but rather it pulses to its maximum diameter before flashing solid, and commences again. The bug is not present in Maps SDK (for Android) **9.4.0**.

Example that I've used as a foundation for implementing a pulsing `LocationComponent`:
https://docs.mapbox.com/android/maps/examples/location-component-custom-pulsing/

As a stop-gap solution, I've remained on Maps SDK (for Android) **9.4.0** where the bug is not present.

**Comment by matt4321** [comment]
I'm getting the same, upgrading to 9.6.0 also contains the bug. The logcat produces the following error:

`
W/Mbgl: {Worker 3}[Style]: Attempt to set an invalid property value -0.005207)
W/Mbgl: {Worker 3}[Style]: Attempt to set an invalid property value -0.009694)
W/Mbgl: {Worker 4}[Style]: Attempt to set an invalid property value -0.009694)
W/Mbgl: {Worker 4}[Style]: Attempt to set an invalid property value -0.015584)
W/Mbgl: {Worker 2}[Style]: Attempt to set an invalid property value -0.015584)
W/Mbgl: {Worker 3}[Style]: Attempt to set an invalid property value -0.022629)
W/Mbgl: {Worker 2}[Style]: Attempt to set an invalid property value -0.022629)
W/Mbgl: {Worker 3}[Style]: Attempt to set an invalid property value -0.030318)
W/Mbgl: {Worker 1}[Style]: Attempt to set an invalid property value -0.030318)
W/Mbgl: {Worker 4}[Style]: Attempt to set an invalid property value -0.039609)
W/Mbgl: {Worker 4}[Style]: Attempt to set an invalid property value -0.039609)
W/Mbgl: {Worker 1}[Style]: Attempt to set an invalid property value -0.050057)
W/Mbgl: {Worker 2}[Style]: Attempt to set an invalid property value -0.050057)
`

I did downgrade to 9.4.0 and that seems to work

**Comment by Chaoba** [comment]
Thanks for reporting, I can reproduce this issue locally, will try to fix it.
