### ISSUE TITLE
"Lato Italic" font not rendering in Android SDK

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-gl-native-android#623]
I am trying to use a font in a `format` expression from the default Mapbox Fontstack. i.e.: `Lato Italic`, but it does not seem to show up in the app. I have tried some other fonts as well with varying results. Some seem to show up, some do not. Am I missing something? 
We are using an offline style which we ship with our app. Do I need to somehow manually add some fonts to the style?

Tested with Mapbox Android SDK 9.5.0 (cannot test on 9.6.0 because of #622)
Device:
Xiaomi Mi A2
Android 10.0

**Mapbox studio**
<img width="147" alt="mapbox studio" src="https://user-images.githubusercontent.com/21218132/98850828-a391e600-2455-11eb-8240-49b8ece961a3.png">

**Android SDK**
<img width="259" alt="android app" src="https://user-images.githubusercontent.com/21218132/98850854-adb3e480-2455-11eb-83c7-2c2e998f7b0e.png">

**Relevant piece of information from the style I am using**
```
{
      "id": "polarsteps_guides_city_names_future_timeline",
      "type": "symbol",
      "source": "guides-source",
      "minzoom": 3,
      "filter": [
        "match",
        [
          "get",
          "data_type"
        ],
        [
          "guide"
        ],
        true,
        false
      ],
      "layout": {
        "text-field": [
          "format",
          [
            "to-string",
            [
              "get",
              "name"
            ]
          ],
          {},
          "\n",
          {},
          [
            "to-string",
            [
              "get",
              "tooltip"
            ]
          ],
          {
            "text-font": [
              "literal",
              [
                "Lato Italic",
                "Arial Unicode MS Regular"
              ]
            ],
            "font-scale": 0.9,
            "text-color": [
              "rgba",
              255,
              255,
              255,
              0.9
            ]
          }
        ],
        "text-font": [
          "literal",
          [
            "Lato Bold",
            "Arial Unicode MS Regular"
          ]
        ],
        "text-variable-anchor": [
          "top"
        ],
        "text-radial-offset": [
          "interpolate",
          [
            "linear"
          ],
          [
            "zoom"
          ],
          1,
          0.7,
          6.5,
          1.4
        ],
        "text-size": [
          "interpolate",
          [
            "linear"
          ],
          [
            "zoom"
          ],
          6.5,
          12,
          15,
          18
        ],
        "text-padding": 0
      }
```

**Comment by Chaoba** [comment]
Thanks for using mapbox. Have you read the release note for [9.6.0](https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v9.6.0)? We have added GlyphsRasterizationMode and API, I guess you need to set this mode.

**Comment by florianPOLARSTEPS** [comment]
@Chaoba Ah ok. My issue here was with `9.5.0`. I wanted to try `9.6.0` but didn't get far at all since I couldn't seem to render `format` expressions at all in `9.6.0` (#622). 
I will give `9.6.0` another spin and see if those new flags will help.

**Comment by florianPOLARSTEPS** [comment]
@Chaoba `GlyphsRasterizationMode` seems to do the trick, but I am having loads of other issues with `9.6.0` unfortunately.
Furthermore, it would be nice for us to flag `breaking changes` somewhere in a Changelog or at least have a note somewhere in the documentation.
Thanks.

**Comment by bomturbo** [comment]
USS Oklahoma Memorial
Langley Ave, Honolulu, HI 96818 สหรัฐอเมริกา
https://maps.app.goo.gl/TemQ7tTFs5cMTouK7

**Comment by Chaoba** [comment]
@florianPOLARSTEPS If I understand correctly, `GlyphsRasterizationMode` resolves the `format` expression issue, right? And what do you mean 

> but I am having loads of other issues with 9.6.0 unfortunately
