### ISSUE TITLE
Move MapBox Account to Maven Central

### ISSUE THREAD

**Issue by Guimareshh** [mapbox/mapbox-gl-native-android#650]
Hello 👋 

As you may know, JCenter is going to be shutdown very soon (more information [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)). I wanted to do a full migration on my app to remove JCenter, but because of MapBox Account being hosted on JCenter I can't do it. Is it already plan to move on to Maven Central ?

Here is the build error while building the app, just by removing JCenter from the gradle project file
```kotlin
Execution failed for task ':app:dataBindingMergeDependencyArtifactsStagingDebug'.
> Could not resolve all files for configuration ':app:stagingDebugCompileClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :app > com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1
```

Thanks !

**Comment by Guimareshh** [comment]
Hey 👋 It has been almost 2 weeks and no answer on this issue. Can we have at least a reply on what's planed to fix the issue ? Will we have a release for version 9.x.x on Maven Central ? Will we have to migrate to version 10 which is currently in beta ?

Thanks!

**Comment by Chaoba** [comment]
All the packages have been moved to https://api.mapbox.com/downloads/v2/releases/maven, please follow the [configure](https://github.com/mapbox/mapbox-gl-native-android#project-configuration) in README.

**Comment by petedoyle** [comment]
Any chance of not requiring authentication? My hunch is it wasn't a strong requirement for you all, but just happened because it's on api.mapbox.com? Publishing to Maven Central would avoid that.

Asking because it makes it harder to use a caching Maven proxy.

**Comment by Guimareshh** [comment]
Closing the issue as I recently were able to build the app with MapBox after removing `JCenter()`
