### ISSUE TITLE
Optimize for size when building

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native-android#66]
We enable LTO when generating the APK to reduce binary size, but `-Oz` is no longer present in the new build system, causing the binaries for `libmapbox-gl.so` on arm64-v8a jump from 1.8MB to 2.5MB (compressed).

The new build system abides by the [Android NDK CMake toolchain](https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake#475) optimization flag rules. However, given the binary size increase, I'd suggest sticking to overriding these with `-Oz` like the previous build system.

**Comment by zugaldia** [comment]
>  I'd suggest sticking to overriding these with -Oz like the previous build system.

This makes sense to me. I wonder though why the default Android NDK CMake settings wouldn't do this as well. Are there any downsides that we should be aware of or document?

cc: @mapbox/maps-android

**Comment by tobrun** [comment]
adressed with https://github.com/mapbox/mapbox-gl-native-android/pull/382
