### ISSUE TITLE
Still Get Telemetery Crash in android 11 Compile SDK 30 , Mapbox version 9.6.2

### ISSUE THREAD

**Issue by soobasa** [mapbox/mapbox-gl-native-android#700]
@tobrun
Hi , 
im still having issue ,

dependencies :
implementation `'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2' implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'`
gradlew app:dependencies :
`+--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2
|    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry-okhttp3:8.1.0
|    |    +--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.14.4
|    |    |    \--- com.squareup.okio:okio:1.17.2
|    |    +--- androidx.core:core:1.5.0 (*)
|    |    +--- com.google.code.gson:gson:2.8.5 -> 2.8.6
|    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    +--- com.mapbox.mapboxsdk:mapbox-android-core:5.0.0
|    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-android-core:5.0.0
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
|    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.2.2
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0
|    |    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0 (*)
|    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    +--- androidx.fragment:fragment:1.0.0 -> 1.3.6 (*)
|    \--- com.squareup.okhttp3:okhttp:3.12.3 -> 3.14.4 (*)
+--- com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0 -> 9.6.2 (*)
|    +--- androidx.appcompat:appcompat:1.0.0 -> 1.3.1 (*)
|    +--- androidx.constraintlayout:constraintlayout:1.1.3 -> 2.1.0 (*)
|    +--- androidx.cardview:cardview:1.0.0 (*)
|    +--- androidx.recyclerview:recyclerview:1.0.0 -> 1.2.1 (*)
|    +--- androidx.legacy:legacy-support-v4:1.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    +--- androidx.media:media:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0 -> 1.1.1 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    +--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.viewpager:viewpager:1.0.0 (*)
|    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0 (*)
|    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    |    \--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0 (*)
|    |    \--- androidx.fragment:fragment:1.0.0 -> 1.3.6 (*)
|    +--- com.google.android.material:material:1.0.0 -> 1.4.0 (*)
|    +--- com.jakewharton.timber:timber:4.7.1
|    |    \--- org.jetbrains:annotations:16.0.1
|    +--- androidx.lifecycle:lifecycle-extensions:2.0.0
|    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.3.1 (*)
|    |    +--- androidx.arch.core:core-common:2.0.0 -> 2.1.0 (*)
|    |    +--- androidx.arch.core:core-runtime:2.0.0 -> 2.1.0 (*)
|    |    +--- androidx.fragment:fragment:1.0.0 -> 1.3.6 (*)
|    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.3.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0 -> 2.1.0 (*)
|    |    +--- androidx.lifecycle:lifecycle-process:2.0.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.3.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-service:2.0.0 -> 2.1.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.1.0 -> 2.3.1 (*)
|    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 -> 2.3.1 (*)
|    +--- androidx.room:room-runtime:2.0.0 -> 2.2.5
|    |    +--- androidx.room:room-common:[2.2.5] -> 2.2.5
|    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    +--- androidx.sqlite:sqlite-framework:2.0.1 -> 2.1.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    \--- androidx.sqlite:sqlite:[2.1.0] -> 2.1.0
|    |    |         \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    +--- androidx.sqlite:sqlite:2.0.1 -> 2.1.0 (*)
|    |    \--- androidx.arch.core:core-runtime:2.0.1 -> 2.1.0 (*)
|    \--- com.mapbox.mapboxsdk:mapbox-sdk-services:5.1.0
|         +--- com.mapbox.mapboxsdk:mapbox-sdk-core:5.1.0
|         |    +--- com.google.code.gson:gson:2.8.6
|         |    +--- com.squareup.retrofit2:retrofit:2.7.1
|         |    |    \--- com.squareup.okhttp3:okhttp:3.14.4 (*)
|         |    +--- com.squareup.retrofit2:converter-gson:2.7.1
|         |    |    +--- com.squareup.retrofit2:retrofit:2.7.1 (*)
|         |    |    \--- com.google.code.gson:gson:2.8.5 -> 2.8.6
|         |    \--- com.squareup.okhttp3:logging-interceptor:3.12.7
|         |         \--- com.squareup.okhttp3:okhttp:3.12.7 -> 3.14.4 (*)
|         +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.1.0 -> 5.3.0 (*)
|         +--- com.mapbox.mapboxsdk:mapbox-sdk-directions-models:5.1.0
|         |    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.1.0 -> 5.3.0 (*)
|         |    \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|         \--- com.mapbox.mapboxsdk:mapbox-sdk-directions-refresh-models:5.1.0
|              +--- com.mapbox.mapboxsdk:mapbox-sdk-directions-models:5.1.0 (*)
|              \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
+--- com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0
|    +--- androidx.appcompat:appcompat:1.0.0 -> 1.3.1 (*)
|    \--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0 -> 9.6.2 (*)`

Compile /TARGET SDK VERSION :
30

TEST : Smamsun A20 Android 11 , Android Stuido Emulator API 30

Error :
E/MapboxTelemetry: java.lang.ExceptionInInitializerError E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException

NOTE : IF I set comile / sdk version to 29 every thing is perfect but i cant release my app update too googleplay due to new policies
NOTE2 : it is having problem on fresh install and show error on fresh install of app , not updated ones .

**Comment by tobrun** [comment]
> E/MapboxTelemetry: java.lang.ExceptionInInitializerError E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException

Would you be able to share the full stacktrace?

**Comment by soobasa** [comment]
@tobrun  ,  i fixed the problem , just in case anyone find this from search engines 

when use mapbox 
mapbox-android-plugin-places
com.mapbox.mapboxsdk:mapbox-android-plugin-annotation

with original mapbox sdk 

some libraries cant work together 

you should : 
exclude 
module: 'mapbox-android-telemetry'
module: 'mapbox-android-sdk'
module: 'mapbox-sdk-core'

from places and announction plugins to fix the problem 
```
implementation('com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0') {
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry'
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-sdk-core'
    }
```
