### ISSUE TITLE
Location reuses feature object

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#702]
We have a raise condition on the location component feature. Currently we reuse the features object and pass that to gl-native. gl-native however parses this asynchronous and by that time we could already have updated it on the main thread. This currently results in a crash and is something we want to patch. 

The feature object mentioned can be found in https://github.com/mapbox/mapbox-gl-native-android/blob/3467eefe5d5f66240107b123be4b7dd62564aed0/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/SymbolLocationLayerRenderer.java#L69

**Comment by pengdev** [comment]
Closed by https://github.com/mapbox/mapbox-gl-native-android/pull/703
