### ISSUE TITLE
[Bug] High contrast text showing bold in v9.6.1+

### ISSUE THREAD

**Issue by tsuz** [mapbox/mapbox-gl-native-android#711]
**Expected/Observed**

| Expected | Observed |
|--|--|
| ![Screenshot_20211008-143208](https://user-images.githubusercontent.com/6927131/136503648-8813b872-1c05-431e-a55b-58731979cb8c.png) | ![Screenshot_20211008-142945](https://user-images.githubusercontent.com/6927131/136503643-d9a11238-c996-4741-8a83-46da78237503.png) |

**Reproduce Steps**

1. Open Android's settings and enable high contrast text ([guide][1])
1. Open android demo example: https://github.com/mapbox/mapbox-android-demo
1. Install maps 9.6.1 or higher
1. Build, run and open `A simple map view`
1. Go to a region that has CJK text (i.e. Tokyo)
1. Notice the text is bold

**Additional Context**

- Previously, this issue was fixed via https://github.com/mapbox/mapbox-gl-native-android/pull/50

| Version | Occurrence |
|--|--|
| v9.7.0 | 🐞 |
| v9.6.1 | 🐞 |
| v9.6.0 | 🆗 |

**Impact**

CJK users are unable to upgrade to v9.6.1 or higher

[1]: https://support.google.com/accessibility/android/answer/11183305?hl=en&visit_id=637692671513295921-2980514359&rd=1

**Comment by ank27** [comment]
@tsuz it is now fixed with the latest release.
