### ISSUE TITLE
Store unstripped release builds

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#72]
To allow symbolicating stacktraces from users we need to store unstripped versions of our shared objects as part of our release process. Ideally we upload these to s3 in a versioned manner. We create these unstripped versions by building with `BUILDTYPE=RelWithDebInfo`.

Additionally, we could create a small tool that takes a given stacktrace and SDK version number to symbolicate the trace. This would make the process of looking into a native crash a little bit easier.

cc @tmpsantos @alexshalamov @mapbox/maps-android

**Comment by alexshalamov** [comment]
@tobrun I was able to symbolicate crashes using unstripped `Release` builds. Are you sure we need `RelWithDebInfo`?

**Comment by tobrun** [comment]
Sounds good @alexshalamov, I will store files from `./platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release/obj/` as CI build artifacts and update our release process to include these files in the github release. 

cc @mapbox/maps-android

**Comment by tobrun** [comment]
@pengdev you are running point on the release this week. Could you include the files mentioned above as part of the github release?

**Comment by langsmith** [comment]
I did the beta.1 release. I added the files to https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v8.6.0-beta.1.

![Screen Shot 2019-12-06 at 1 35 40 PM](https://user-images.githubusercontent.com/4394910/70358047-4fd25200-182d-11ea-8307-b9c4824a53fe.png)

Heads up that ⬆️ is how they're listed in CircleCI. I renamed them to ⬇️ . 

![Screen Shot 2019-12-06 at 1 37 12 PM](https://user-images.githubusercontent.com/4394910/70358140-86a86800-182d-11ea-9aaf-abea3d2c38d9.png)

You might need to rename the file to `libmapbox-gl.so` if you're trying to use it.

**Comment by zugaldia** [comment]
Looks like we're good to close here once that we added this step to our release checklist?

**Comment by tobrun** [comment]
> Looks like we're good to close here once that we added this step to our release checklist?

That already happened, added a link between this issue and the PR updating the documentation.

Good to close, thank you @langsmith for working on this!
