### ISSUE TITLE
jcenter sunset - release code to maven

### ISSUE THREAD

**Issue by felix-ht** [mapbox/mapbox-gl-native-android#721]
With jcenter's sunset imminent it would be great if you could publish all releases to maven instead. This also includes all the sub depencies you control. 

This currently not the case: https://mvnrepository.com/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk

So please release new versions of 9.x.x and 10.x.x to maven. 

Here is a example of a failing build from [flutter mapbox gl](https://github.com/flutter-mapbox-gl/maps/runs/4843607549?check_suite_focus=true) @Chaoba

**Comment by Chaoba** [comment]
@felix-ht We have transferred to Mapbox api download and already have the [config](https://github.com/flutter-mapbox-gl/maps/blob/689933a456a21dff626e38741cbdec9b64937d9e/android/build.gradle#L23) in flutter mapbox gl .

Guess you need to rebase your branch.

**Comment by felix-ht** [comment]
The branch is rebased https://github.com/flutter-mapbox-gl/maps/blob/annotation-in-dart/android/build.gradle 
Seems to be a more general issue.

**Comment by felix-ht** [comment]
seems to work fine today without any changes - no idea what changed
