### ISSUE TITLE
Migrating to AndroidX

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#79]
We are currently relying on android support packages and okhttp 3.12.x versions. These dependencies have become obsolete and have been replaced by more modern equivalents. To make this repository future proof, we need to invest updating our codebase to support AndroidX and OkHttp 4.x while also being able to support users with current configuration requirements.

**Comment by tobrun** [comment]
Updating the title to only AndroidX and removing references to OkHttp. Bumping OkHttp will result in increasing the min SDK version and OkHttp 3.12.x releases will remain valid until end of 2020.

**Comment by mansoordxb** [comment]
Thanks
