### ISSUE TITLE
Use synchronous OkHttp

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native-android#82]
Noticing that we use asynchronous OkHttp setup while the HttpRequesImpl will get executed on a worker thread. Since there is no need for async setup we can rework our setup to be synchronous. We can run benchmarks to validate if we get any performance improvements from these. 

cc @mapbox/maps-android

**Comment by maxtracking** [comment]
@tobrun Any updates on this? Also, maybe it's time to update OkHttp version to their latest as well?

**Comment by tobrun** [comment]
It's expected behavior from gl-native that a http request will spawn it's own thread. If we use the gl-native provided thread, we can't request multiple resources at once. The filsource will wait to schedule a new request until the previous request has completed.

> `update OkHttp version`

@maxtracking sadly we can't, current OkHttp version is a LTS version that works on API 14+ 
We can't bump it as our min version would become lolipop.

**Comment by zugaldia** [comment]
While we can't bump the OkHttp version bundled with the SDK, the developer can always invoke [`HttpRequestUtil.setOkHttpClient(OkHttpClient client)`](https://docs.mapbox.com/android/api/map-sdk/9.0.0/com/mapbox/mapboxsdk/module/http/HttpRequestUtil.html#setOkHttpClient-OkHttpClient-) to set their own client/version.
