### ISSUE TITLE
How to disable telemetry ?

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-gl-native-android#90]
The sdk documentation is pretty vague about that.

I am using the sdk in version 8.4.0
What is the official way to disable telemetry ?
It looks like it is disabled with only this line
TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED);

What is the difference with ?
Mapbox.getTelemetry().setUserTelemetryRequestState(false);

Thanks

**Comment by LukasPaczos** [comment]
Hey @ben-j69, `Mapbox.getTelemetry().setUserTelemetryRequestState(false);` calls into `TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED);` and additionally does other work.

So the correct way would be to only call `Mapbox.getTelemetry().setUserTelemetryRequestState(false);`.
