### ISSUE TITLE
Transifex configuration missing

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native-android#96]
.tx/config was removed in a3ef1ac2d0a7ee28404573a5fc256dda9f562f60. This file is used for configuring the pulling of translated strings from Transifex. The various iOS/macOS file paths can be removed safely, but the Android path should be restored. (This is the path being removed from the iOS/macOS repository in mapbox/mapbox-gl-native-ios#93.)

/cc @mapbox/maps-android

**Comment by zugaldia** [comment]
Thank you @1ec5 for flagging. I've added the ticket to our board for prioritization. This items should be considered part of the monorepo migration work (https://github.com/mapbox/mapbox-gl-native/issues/15971).
